# -*- coding: utf-8 -*-
"""kneexray.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1utcLThhwXBtao_wkBLLf0bW_jVhjpH6M
"""

!unzip /content/converted_savedmodel.zip -d models

from keras.models import load_model
from PIL import Image, ImageOps
import numpy as np

# Load the model
model = load_model('/content/models/model.savedmodel/')

from keras.models import load_model
from PIL import Image, ImageOps
import numpy as np

# Create the array of the right shape to feed into the keras model
# The 'length' or number of images you can put into the array is
# determined by the first position in the shape tuple, in this case 1.
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
# Replace this with the path to your image
image = Image.open('/content/SevereG4 (3).png')
#resize the image to a 224x224 with the same strategy as in TM2:
#resizing the image to be at least 224x224 and then cropping from the center
size = (224, 224)
image = ImageOps.fit(image, size, Image.ANTIALIAS)

#turn the image into a numpy array
image_array = np.asarray(image)
# Normalize the image
normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
# Load the image into the array
data[0] = normalized_image_array

# run the inference
prediction = model.predict(data)
print(prediction)

result=np.argmax(prediction)

print ('classification result=',result)



def map(result):
  if result==0:
    print("its Normal ")
    mapped="Normal knee"
  elif result==1 :
    print("its a Doubtful ")
    mapped="Doubtful knee"
  elif result ==2 : 
    print("its a Mild")
    mapped="Mild knee"
  elif result ==3 : 
    print("its a moderate ")
    mapped="moderate knee"

  else :
    print("sever")
    mapped="sever knee"

  return mapped

pth='/content/SevereG4 (3).png'
font=cv2.FONT_HERSHEY_SIMPLEX
fontScale=2
fontColor=(255,255,255)
org=(443,320)
text = str(map(result))
im = cv2.imread(pth, 1)

x=cv2.putText(im,str(text), (32,32),cv2.FONT_HERSHEY_SIMPLEX, 1, 255)
cv2.imwrite('sever2knee.jpg', x)

